spring:
  datasource:
    host: localhost
    port: 5432
    database: /*%= getDatabaseConfigFromSpec(data, 'database', 'gema') %*/
    username: postgres
    password: postgres
    url: jdbc:postgresql://${spring.datasource.host}:${spring.datasource.port}/${spring.datasource.database}
    hikari:
      connectionTimeout: 20000
      maximumPoolSize: 5
  /*% if (feature.MWM_TA_TrajectoryAnnotator || feature.UserManagement || feature.UM_AccountActivation || feature.T_FileUploader || feature.MV_MS_GJ_Cached) { %*/
  quartz:
    job-store-type: jdbc
    properties:
      org:
        quartz:
          threadPool:
            class: org.quartz.simpl.SimpleThreadPool
            threadCount: 10
            threadsInheritContextClassLoaderOfInitializingThread: true
          jobStore:
            class: org.springframework.scheduling.quartz.LocalDataSourceJobStore
            driverDelegateClass: org.quartz.impl.jdbcjobstore.PostgreSQLDelegate
            useProperties: false
  /*% } %*/
  jpa:
    defer-datasource-initialization: true
    open-in-view: false
    hibernate:
      ddl-auto: update
    properties:
      hibernate.jdbc.lob.non_contextual_creation: true
      hibernate.temp.use_jdbc_metadata_defaults: true
      hibernate.dialect: org.hibernate.spatial.dialect.postgis.PostgisDialect
  /*% if (feature.T_MailSender) { %*/
  # Email server configuration
  mail:
    host: 127.0.0.1
    username: dummy
    password: dummy
    port: 25
    from: no-reply@dummyserver.es
  # Email templates configuration
  thymeleaf:
    mode: HTML
    cache: true
  /*% } %*/
  servlet:
    multipart:
      max-file-size: 250MB     # Set MAX_UPLOAD_FILE_SIZE in gulpfile.js
      max-request-size: 260MB  # max-file-size + 10
  sql:
    init:
      encoding: UTF-8
      mode: always
      continue-on-error: true
  /*% if (feature.MV_MS_GJ_Cached) { %*/
  # Static files configuration
  mvc:
    static-path-pattern: /api/geometries/**
  web:
    resources:
      cache:
        cachecontrol:
          max-age: 365d
      static-locations[0]: file:src/main/resources/spatial/
      static-locations[1]: classpath:/spatial/
  /*% } %*/
/*% if (feature.SensorViewer) { %*/
/*% var hasElasticSensor = data?.dataWarehouse?.sensors?.find(function(sensor) { return sensor.datasource === 'elasticsearch'; }) !== undefined; %*/
/*% if (hasElasticSensor) { %*/
  elasticsearch:
    rest:
      uris: /*%= data.basicData.elastic.uris %*/
      username: /*%= data.basicData.elastic.username %*/
      password: /*%= data.basicData.elastic.password %*/
      connection-timeout: 15000
      read-timeout: 15000
/*% } %*/
/*% } %*/
server:
  compression:
    enabled: true
    mime-types: text/html,text/xml,text/plain,text/css, application/javascript, application/json
    min-response-size: 1024
  uploads: upload
  temporaryUploads: temporary
  #Default internal page size (Used for some high database usage methods)
  pageSize: 3
  port: 8080
/*% if (feature.UserManagement) { %*/
initDB:
  defaultAdminUser: admin
  defaultAdminPassword: admin
  defaultAdminEmail: admin@localhost
/*% } %*/
security-properties:
  /*% if (feature.UserManagement) { %*/
  security:
    /*% if (feature.UM_ST_JWT) { %*/
    jwtSecretKey: +hxpNwFEwpJWbZQnff+k6Lm2VOExdGoPgYxZg3zeoz97iOK/lL/ZctLRXQpoElRoXR841LImSZzmf+WtGTA9QGGxpgUkKV1/fSyXVIOVqsYZpdK/oj0NKfu1Eu665Tb6jgrsYjr5/fLKB1llmjPCjBAbIu9OW8UMrJTLD/MUyy4wPWoFCEf3uBmLaVBsU751Mpw1rJc9p/1TfbUf4lli5eJhPic1mdIRrwpclQ==
    jwtValidity: 604800
      /*% if (feature.UM_A_RememberPass) { %*/
    shortJwtValidity: 3600
      /*% } %*/
    /*% } %*/
  /*% } %*/
logging:
  level:
    root: INFO
    es.udc.lbd.gema.lps: DEBUG
    es.udc.lbd.gema.lps.model.util.EnumConverter: ERROR
properties:
  clientHost: http://localhost:1234
/*% if (feature.T_GIS) { %*/
  gis:
    defaultSrid: /*%= data.basicData.SRID || 4326  %*/
/*% } %*/
  environment: dev
/*% if (feature.MWM_TE_T_ClientCustomLink) { %*/
trajectory-exploitation:
  detailUrl: ${properties.clientHost}/staff/clients/{id}
/*% } %*/
/*% if (feature.MWM_VisitSchedule) { %*/
event-calendar:
  event-day-size-threshold: 20
  event-week-size-threshold: 140
/*% } %*/
/*% if (feature.MV_MS_GeoServer) { %*/

geoserver:
  # GeoServer url also goes to gulp/config.js
  active: true
  url: http://localhost:9001/geoserver
  user: admin
  password: geoserver
  workspace: /*%= normalize(data.basicData.packageInfo.artifact) %*/
  datastore: /*%= normalize(data.basicData.packageInfo.artifact) %*/
/*% } %*/
/*% if (feature.T_P_PayPal) { %*/
paypal:
  clientId: clientId
  secret: secret
/*% } %*/
/*% if (feature.T_P_RedSys) { %*/
redsys:
  currency: 978
  key: key
  merchantcode: 000000000
  publicClientUrl: ${properties.clientHost}
  publicServerUrl: http://localhost:8080/api
  terminal: '001'
/*% } %*/
