env:
  node: true
  es2021: true
extends:
  - eslint:recommended
  - prettier
  - plugin:vue/base
  - plugin:vuetify/base
overrides: []
parserOptions:
  ecmaVersion: latest
  sourceType: module
rules: {}
