version: '3.8'

services:
  sensor-builder:
    container_name: sensor-builder-client
    build:
      context: ./src # Replace this with the path to your Vue + Vite app
      dockerfile: Dockerfile
    volumes:
      - ".:/app" # Mount the entire project directory to /app in the container
    ports:
      - "5000:5000" # Map the Express Node server port
    environment:
      - PORT=5000
      - CLIENT_URL=http://localhost:5173
    networks:
      - local

networks:
  local:
    driver: bridge
